plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

packageExtensions:
  "typed-design-system@*":
    dependencies:
      "@emotion/core": "~10.0.0"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
